name: CI

on: [push, pull_request]  # Trigger the build on every push or pull request

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Linux environment for the build
    steps:
    - uses: actions/checkout@v2  # Check out the code from your repository
    
    - name: Set up JDK 11  # Set up Java Development Kit (JDK) version 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Gradle  # Run the Gradle build process
      run: ./gradlew build
